### ISSUE TITLE
Doesn't build on 2019.11

### ISSUE THREAD

**Issue by colomon** [Kaiepi/p6-Trait-Traced#2]
I finally got around to updating my rakudo after Trait::Traced didn't pass tests on my 2018.12 version.  Unfortunately it doesn't even build on my 2019.11:

```
[Trait::Traced] ===SORRY!=== Error while compiling /Users/colomon/.zef/store/Trait-Traced-0.1.0.tar.gz/Trait-Traced-0.1.0/lib/Traced.pm6 (Traced)
[Trait::Traced] Confused
[Trait::Traced] at /Users/colomon/.zef/store/Trait-Traced-0.1.0.tar.gz/Trait-Traced-0.1.0/lib/Traced.pm6 (Traced):59
[Trait::Traced] ------>         take ' ' x 4 ~ $_ for @.entries:⏏ :$tty;
[Trait::Traced]     expecting any of:
[Trait::Traced]         colon pair
```

**Comment by Kaiepi** [comment]
Thanks for the report. It looks like using `$.`/`@.`/`%.`/`&.` syntax in combination with colon syntax for method calls is what's making the compiler unhappy, so I'll try changing it to use `self` instead and see if that builds on 2019.11.

**Comment by Kaiepi** [comment]
v0.1.1 will be up on CPAN shortly, which fixes this. Let me know if any tests fail, as this module currently depends on NativeCall to handle trace output to standard streams in a thread-safe manner, which is a dependency I plan on removing in v0.2.0.

**Comment by colomon** [comment]
I actually installed your latest from github and it worked fine for me.
Thanks!
